#!/data/data/com.termux/files/usr/bin/bash -e


echo "
[*] Extracting rootfs...
"
proot --link2symlink tar -xJf "$IMAGE_NAME" >/dev/null 2>&1

###
cat > ${PREFIX}/bin/nethunter <<- EOF
#!/data/data/com.termux/files/usr/bin/bash -e
cd \${HOME}
## termux-exec sets LD_PRELOAD so let's unset it before continuing
unset LD_PRELOAD
## Workaround for Libreoffice, also needs to bind a fake /proc/version
if [ ! -f chroot/kali-arm64/root/.version ]; then
    touch chroot/kali-arm64/root/.version
fi

## Default user is "kali"
user="kali"
home="/home/\$user"
start="sudo -u kali /bin/bash"

## NH can be launched as root with the "-r" cmd attribute
## Also check if user kali exists, if not start as root
if grep -q "kali" chroot/kali-arm64/etc/passwd; then
    KALIUSR="1";
else
    KALIUSR="0";
fi
if [[ \$KALIUSR == "0" || ("\$#" != "0" && ("\$1" == "-r" || "\$1" == "-R")) ]];then
    user="root"
    home="/\kali"
    start="/bin/bash --login"
    if [[ "\$#" != "0" && ("\$1" == "-r" || "\$1" == "-R") ]];then
        shift
    fi
fi

cmdline="proot \\
        --link2symlink \\
        -0 \\
        -r chroot/kali-arm64 \\
        -b /dev \\
        -b /proc \\
        -b /sdcard \\
        -b chroot/kali-arm64\/kali:/dev/shm \\
        -w \/kali \\
           /usr/bin/env -i \\
           HOME=\/kali \\
           PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin \\
           TERM=\$TERM \\
           LANG=C.UTF-8 \\
           \$start"

cmd="\$@"
if [ "\$#" == "0" ];then
    exec \$cmdline
else
    \$cmdline -c "\$cmd"
fi
EOF

chmod 700 "${PREFIX}/bin/nethunter"
##
ln -s "${PREFIX}/bin/nethunter" "${PREFIX}/bin/nh"
##

cat > chroot/kali-arm64/usr/bin/kex <<- EOF
#!/bin/bash

function start-kex() {
    if [ ! -f ~/.vnc/passwd ]; then
        passwd-kex
    fi
    USR=\$(whoami)
    if [ \$USR == "root" ]; then
        SCREEN=":2"
    else
        SCREEN=":1"
    fi 
    export MOZ_FAKE_NO_SANDBOX=1; export HOME=\${HOME}; export USER=\${USR}; LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libgcc_s.so.1 nohup vncserver \$SCREEN >/dev/null 2>&1 </dev/null
    starting_kex=1
    return 0
}

function stop-kex() {
    vncserver -kill :1 | sed s/"Xtigervnc"/"NetHunter KeX"/
    vncserver -kill :2 | sed s/"Xtigervnc"/"NetHunter KeX"/
    return $?
}

function passwd-kex() {
    vncpasswd
    return $?
}

function status-kex() {
    sessions=\$(vncserver -list | sed s/"TigerVNC"/"NetHunter KeX"/)
    if [[ \$sessions == *"590"* ]]; then
        printf "\n\${sessions}\n"
        printf "\nYou can use the KeX client to connect to any of these displays.\n\n"
    else
        if [ ! -z \$starting_kex ]; then
            printf '\nError starting the KeX server.\nPlease try "nethunter kex kill" or restart your termux session and try again.\n\n'
        fi
    fi
    return 0
}

function kill-kex() {
    pkill Xtigervnc
    return \$?
}

case \$1 in
    start)
        start-kex
        ;;
    stop)
        stop-kex
        ;;
    status)
        status-kex
        ;;
    passwd)
        passwd-kex
        ;;
    kill)
        kill-kex
        ;;
    *)
        stop-kex
        start-kex
        status-kex
        ;;
esac
EOF

#
    chmod 700 chroot/kali-arm64/usr/bin/kex

    ## Prevent attempt to create links in read only filesystem
    if [ -f chroot/kali-arm64/root/.bash_profile ]; then
        sed -i '/if/,/fi/d' "chroot/kali-arm64/root/.bash_profile"
    fi
    ## We don't have systemd so let's use static entries for Quad9 DNS servers
    echo "nameserver 9.9.9.9" > chroot/kali-arm64/etc/resolv.conf
    echo "nameserver 149.112.112.112" >> chroot/kali-arm64/etc/resolv.conf

    ## fix sudo & su on start
    chmod +s chroot/kali-arm64/usr/bin/sudo
    chmod +s chroot/kali-arm64/usr/bin/su
    echo "kali    ALL=(ALL:ALL) ALL" > chroot/kali-arm64/etc/sudoers.d/kali
    echo "Set disable_coredump false" > chroot/kali-arm64/etc/sudo.conf

    ## Change kali uid and gid to match that of the termux user
    USRID=$(id -u)
    GRPID=$(id -g)
    nh -r usermod -u "$USRID" kali 2>/dev/null
    nh -r groupmod -g "$GRPID" kali 2>/dev/null

cd ${HOME}

echo "
Done 👍 
"

