#!/bin/sh

cd $HOME
###
wget -O $PREFIX/bin/nethunter https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/Chroot/nethunter
###
cp $PREFIX/bin/nethunter $PREFIX/bin/nh
###
chmod 700 $PREFIX/bin/nethunter
###
chmod 700 $PREFIX/bin/nh
###
wget https://kali.download/nethunter-images/current/rootfs/kali-nethunter-rootfs-full-arm64.tar.xz
###
tar -xvJf kali-nethunter-rootfs-full-arm64.tar.xz
###
echo "
errors doesn't affect root file system
"
###
echo "
        To Login 👇
user terminal: "nethunter / nh"
root terminal: "nethunter -r / nh -r"
"
