#!/bin/sh

cd $HOME
###
wget -O $PREFIX/bin/nethunter https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/Chroot/nethunter
###
cp -r $PREFIX/bin/nethunter $PREFIX/bin/kali
###
chmod 700 $PREFIX/bin/nethunter
###
chmod 700 $PREFIX/bin/kali
###
axel -a -n 6 -o kali-minimal.tar.xz https://kali.download/nethunter-images/current/rootfs/kali-nethunter-rootfs-minimal-arm64.tar.xz
###
echo "
[*] Extracting rootfs...
"
###
bsdtar -xpJf kali-minimal.tar.xz &>/dev/null
###
echo "
[*] Done!
"
###
echo "
To Login 👇
user: "kali"
root: "kali -r"
"

