#!/data/data/com.termux/files/usr/bin/bash -e

cd $HOME
###
axel -a -n 1 -o kali-full.tar.xz https://kali.download/nethunter-images/current/rootfs/kali-nethunter-rootfs-full-arm64.tar.xz
###
echo "
[*] Extracting rootfs...!!!
"
proot --link2symlink bsdtar -xpJf kali-full.tar.xz 2> /dev/null
###
sleep 2s
###
echo "
[*] Extraction Done!
"
###
wget -O chroot/kali-arm64/bin/kex https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/Chroot/kex
###
chmod 700 chroot/kali-arm64/bin/kex
###
wget -O $PREFIX/bin/nethunter https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/Chroot/nethunter
###
chmod 700 $PREFIX/bin/nethunter
###
ln -s $PREFIX/bin/nethunter $PREFIX/bin/nh
###
cd $HOME
###
sed -i '/if/,/fi/d' chroot/kali-arm64/root/.bash_profile
###
echo "nameserver 9.9.9.9" > chroot/kali-arm64/etc/resolv.conf
echo "nameserver 8.8.4.4" >> chroot/kali-arm64/etc/resolv.conf
###
chmod +s chroot/kali-arm64/usr/bin/sudo
###
chmod +s chroot/kali-arm64/usr/bin/su
###
echo "kali    ALL=(ALL:ALL) ALL" > chroot/kali-arm64/etc/sudoers.d/kali
###
USRID=$(id -u)
GRPID=$(id -g)
nh -r usermod -u "$USRID" kali 2>/dev/null
nh -r groupmod -g "$GRPID" kali 2>/dev/null
echo "
[*] Installation Done!
[*] Type:"nh kex passwd" for vnc
[*] Type:"nh -r kex &" to run vnc
"
