#!/bin/sh

cd $HOME
###
wget -O $PREFIX/bin/nethunter https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/Chroot/nethunter
###
cp -r $PREFIX/bin/nethunter $PREFIX/bin/kali
###
chmod 700 $PREFIX/bin/nethunter
###
chmod 700 $PREFIX/bin/kali
###
wget -O kali-minimal.tar.xz https://kali.download/nethunter-images/current/rootfs/kali-nethunter-rootfs-minimal-arm64.tar.xz
###
bsdtar -xpf kali-minimal.tar.xz
###
echo "
       To Login 👇
user terminal: "nethunter or kali"
root terminal: "nethunter -r or kali -r"
"

