#!/data/data/com.termux/files/usr/bin/bash -e

cd $HOME

## termux-exec sets LD_PRELOAD so let's unset it before continuing
unset LD_PRELOAD

## Proot
cmdline="proot \
        --link2symlink \
        -0 \
        -L \
        --ashmem-memfd \
        -r kali-arm64 \
        -b /dev \
        -b /proc \
        -b /sys \
        -b /sdcard \
        -b kali-arm64:/dev/shm \
        -w /root \
           /usr/bin/env -i \
           PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin \
           HOME=/root \
           TERM=$TERM \
           LANG=C.UTF-8 \
           /bin/bash --login"

cmd="$@"
if [ "$#" == "0" ];then
    exec $cmdline
else
    $cmdline -c "$cmd"
fi
