#!/bin/sh

cd $HOME
###
wget -O $PREFIX/bin/nethunter https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/Chroot/nethunter
###
chmod 700 $PREFIX/bin/nethunter
###
ln -s $PREFIX/bin/nethunter $PREFIX/bin/kali
###
axel -a -n 1 -o kali-minimal.tar.xz https://kali.download/nethunter-images/current/rootfs/kali-nethunter-rootfs-minimal-arm64.tar.xz
###
echo "
[*] Extracting rootfs...
"
###
proot --link2symlink bsdtar -xpJf kali-minimal.tar.xz 2> /dev/null
###
echo "
[*] Done!
"
###
echo "nameserver 9.9.9.9" >/etc/resolv.conf
###
wget -O chroot/kali-arm64/root/.bashrc https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/rcfiles/rootbash.bashrc
wget -O chroot/kali-arm64/home/kali/.bashrc https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/rcfiles/homebash.bashrc
wget -O chroot/kali-arm64/etc/bash.bashrc https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/rcfiles/etcbash.bashrc
###
echo "
   To Login 👇
user type: "kali"
root type: "kali -r"
"

