#!/data/data/com.termux/files/usr/bin/bash -e

# Install required packages
apt install proot proot-distro bsdtar axel neofetch -y
clear

# List of distros
echo -e '\e[1;96m'
echo "Available Distro to Install:"
echo -e '\e[1;95m'
echo "
alpine    archlinux    artix     backbox   blackarch   centos      chimera

debian    deepin       fedora    debkali   kali        manjaro     openkylin

opensuse  pardus       parrot    ubuntu    void
"
echo -e '\e[0m'

# Prompt the user to input text for FS
echo "Enter Distro Name:"
read FS

# Forward the value of FS to NM
NM="$FS"

# Capitalize the first letter of NM
NM=$(echo "$NM" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')

# Display the values of FS and NM
echo "$FS" > /dev/null
echo "$NM" > /dev/null

# Example usage of the variables
# You can replace this with any command that uses FS and NM
echo "$FS $NM" > /dev/null

# Display neofetch with custom ASCII art
neofetch --ascii_distro "${NM}" -L

# Create necessary directories
mkdir -p "$PREFIX/var/lib/proot-distro/installed-rootfs"

# Change directory
cd "$PREFIX/var/lib/proot-distro/installed-rootfs/"

# Download the rootfs using axel
axel -a -o "${FS}.tar.xz" "https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/${FS}.tar.xz"

# Extract the rootfs
echo "[*] Extracting ${NM} Rootfs...!!!"
proot --link2symlink bsdtar -xpJf "${FS}.tar.xz" 2>/dev/null

# Create a proot-distro configuration file for the Kali minimal rootfs
cat > "$PREFIX/etc/proot-distro/${FS}.sh" << EOF
DISTRO_NAME="${NM} Linux"
TARBALL_URL['aarch64']="https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/${FS}.tar.xz"
TARBALL_SHA256['aarch64']="$(sha256sum "${FS}.tar.xz" | awk '{print $1}')"
EOF

# Update bash.bashrc to show login instructions
cat >> "$PREFIX/etc/bash.bashrc" << EOF
echo -e '\e[1;96m'
echo "To login ${NM} Linux Type: ${FS}"
echo -e '\e[0m'
EOF

# Create a shortcut command to launch the distro
cat > "$PREFIX/bin/${FS}" << EOF
#!/data/data/com.termux/files/usr/bin/bash
proot-distro login ${FS}
EOF

# Fix shebang and set executable permissions
termux-fix-shebang "$PREFIX/bin/${FS}"
chmod 700 "$PREFIX/bin/${FS}"

# Display final instructions
echo -e '\e[1;96m'
echo "To login to ${NM} Linux, type: ${FS}"
echo -e '\e[0m'

# Clean-up tarball
sleep 5s
rm ${FS}.tar.xz
