#!/data/data/com.termux/files/usr/bin/bash -e

mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
echo 'DISTRO_NAME="Parrot Sec"' > $PREFIX/etc/proot-distro/parrot.sh
###
echo "
clear
parrot
" >>$PREFIX/etc/bash.bashrc
###
echo "pd sh parrot" > $PREFIX/bin/parrot
###
chmod 700 $PREFIX/bin/parrot
###
axel -a --search https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/parrot.tar.xz
###
echo "
[*] Extracting rootfs...
"
###
proot --link2symlink bsdtar -xpJf parrot.tar.xz 2>/dev/null
###
sleep 2
###
echo "nameserver 9.9.9.9" > parrot/etc/resolv.conf
###
git clone https://github.com/zsh-users/zsh-autosuggestions parrot/root/.zsh/zsh-autosuggestions
###
echo "
To login Parrot type: parrot
"
