#!/bin/sh

mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
echo 'DISTRO_NAME="Parrot Sec"' >> $PREFIX/etc/proot-distro/parrot.sh
###
echo "pd sh parrot" > $PREFIX/bin/parrot
###
chmod 700 $PREFIX/bin/parrot
###
axel -a -n 1 https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/parrot.tar.xz
###
echo "
[*] Extracting rootfs...
"
bsdtar -xpJf parrot.tar.xz >/dev/null 2>&1
###
echo "
To login Parrot type: parrot
"
