#!/bin/sh

echo 'DISTRO_NAME="Parrot Sec"' >> $PREFIX/etc/proot-distro/parrot.sh
###
echo "pd sh parrot" > $PREFIX/bin/parrot
###
chmod 700 $PREFIX/bin/parrot
###
mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
wget https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/parrot.tar.xz
###
bsdtar -xpJf parrot.tar.xz > /dev/null 2>&1
###
echo "
To login Parrot Sec: parrot
"
