#!/data/data/com.termux/files/usr/bin/bash -e

echo 'DISTRO_NAME="BlackArch Linux"' > $PREFIX/etc/proot-distro/blackarch.sh
###
echo "
clear
blackarch
" >>$PREFIX/etc/bash.bashrc
###
echo "pd sh blackarch" > $PREFIX/bin/blackarch
###
chmod 700 $PREFIX/bin/blackarch
###
mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
axel -a -n 1 https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/blackarch.tar.xz
###
echo "
[*] Extracting rootfs...
"
###
proot --link2symlink bsdtar -xpJf blackarch.tar.xz 2> /dev/null
###
echo "
[*] Done!
"
###
echo "nameserver 9.9.9.9" > blackarch/etc/resolv.conf
###
echo "
To login Blackarch type: blackarch
"
