#!/data/data/com.termux/files/usr/bin/bash -e
cd ${HOME}
## termux-exec sets LD_PRELOAD so let's unset it before continuing
unset LD_PRELOAD
## Workaround for Libreoffice, also needs to bind a fake /proc/version
if [ ! -f $PREFIX/var/lib/proot-distro/installed-rootfs/backbox/root/.version ]; then
    touch $PREFIX/var/lib/proot-distro/installed-rootfs/backbox/root/.version
fi

## Also check if user is exists, if not start as root
 if grep -q "password" $PREFIX/var/lib/proot-distro/installed-rootfs/backbox/etc/passwd; then
    USR="1";
else

    USR="0";
fi
if [[ $USR == "0" || ("$#" != "0" && ("$1" == "-r" || "$1" == "-R")) ]];then
    user=""
    home="/$user"
    start="/bin/bash --login"
    if [[ "$#" != "0" && ("$1" == "-r" || "$1" == "-R") ]];then
        shift
    fi
fi

cmdline="proot \
        --link2symlink \
        -0 \
        -r $PREFIX/var/lib/proot-distro/installed-rootfs/backbox \
        -b /dev \
        -b /proc \
        -b /sdcard \
        -b $PREFIX/var/lib/proot-distro/installed-rootfs/backbox$home:/dev/shm \
        -w $home \
           /usr/bin/env -i \
           HOME=$home \
           PATH=/usr/local/sbin:/usr/local/bin:/bin:/usr/bin:/sbin:/usr/sbin \
           TERM=$TERM \
           LANG=C.UTF-8 \
           $start"

cmd="$@"
if [ "$#" == "0" ];then
    exec $cmdline
else
    $cmdline -c "$cmd"
fi
