#!/data/data/com.termux/files/usr/bin/bash -e

echo 'DISTRO_NAME="BackBox Linux"' > $PREFIX/etc/proot-distro/backbox.sh
###
echo "
clear
backbox
" >>$PREFIX/etc/bash.bashrc
###
echo "pd sh backbox" > $PREFIX/bin/backbox
###
chmod 700 $PREFIX/bin/backbox
###
mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
axel -a --search https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/backbox.tar.xz
###
echo "
[*] Extracting rootfs...
"
###
proot --link2symlink bsdtar -xpJf backbox.tar.xz 2>/dev/null
###
echo "
[*] Done!
"
###
echo "nameserver 9.9.9.9" > backbox/etc/resolv.conf
###
echo "
To login BackBox type: backbox
"
