#!/bin/sh

echo 'DISTRO_NAME="BackBox Linux"' >> $PREFIX/etc/proot-distro/backbox.sh
###
echo "pd sh backbox" > $PREFIX/bin/backbox
###
chmod 700 $PREFIX/bin/backbox
###
mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
axel -a -n 1 https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/backbox.tar.xz
###
echo "
[*] Extracting rootfs...
"
###
bsdtar -xpJf backbox.tar.xz >/dev/null 2>&1
###
echo "
[*] Done!
"
###
echo "
To login BackBox type: backbox
"
