#!/bin/sh

echo 'DISTRO_NAME="Debian Nethunter"' >> $PREFIX/etc/proot-distro/debkali.sh
###
echo "pd sh debkali" > $PREFIX/bin/debkali
###
chmod 700 $PREFIX/bin/debkali
###
mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
wget https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/debkali.tar.xz
###
bsdtar -xpf debkali.tar.xz
###
echo "
To login Parrot Sec: debkali
"
