#!/bin/sh

echo 'DISTRO_NAME="Debian Kali"' >> $PREFIX/etc/proot-distro/debkali.sh
###
mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
wget https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/debkali.tar.xz
###
tar -xvJf debkali.tar.xz
###
echo "
To login Parrot Sec: pd sh parrot
"
pd sh debkali

