#!/data/data/com.termux/files/usr/bin/bash -e

FS=artix
###
apt install proot proot-distro bsdtar xz-utils axel -y
###
mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
axel -a --search https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/$FS.tar.xz
###
echo "
[*] Extracting rootfs...!!!
"
###
proot --link2symlink bsdtar -xpJf $FS.tar.xz 2>/dev/null
###
cat >$PREFIX/etc/proot-distro/$FS.sh << EOF
DISTRO_NAME="Artix Linux"
EOF
###
echo "
clear
alpine
" >>$PREFIX/etc/bash.bashrc
###
echo "pd sh $FS" > $PREFIX/bin/$FS
termux-fix-shebang $PREFIX/bin/$FS
chmod 700 $PREFIX/bin/$FS
###
echo "
To login Artix Linux type: $FS
"
