#!/bin/sh

cd $PREFIX/etc/proot-distro/
###
wget https://raw.githubusercontent.com/xiv3r/Kali-Linux-Nethunter/refs/heads/main/kali/kali-full.sh
###
wget https://raw.githubusercontent.com/xiv3r/Kali-Linux-Nethunter/refs/heads/main/kali/kali-minimal.sh
###
proot-distro list
##$
echo "
To install 👇
187MB: pd i kali-minimal 
 11GB: pd i kali    
"
###
read -p "Enter command: " command
eval "$command"
