#!/data/data/com.termux/files/usr/bin/bash -e


echo 'DISTRO_NAME="Kali Nethunter"' >>$PREFIX/etc/proot-distro/kali.sh
###
echo "pd sh kali" >> $PREFIX/bin/kali
###
chmod 700 $PREFIX/bin/kali
###
mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs/kali
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
axel -a -n 1 -o kali.tar.xz https://kali.download/nethunter-images/current/rootfs/kali-nethunter-rootfs-full-arm64.tar.xz
###
echo "
[*] Extracting rootfs...!!!
"
###
proot --link2symlink bsdtar -xpJf kali.tar.xz 2>/dev/null
###
mv chroot/kali-arm64/* $PREFIX/var/lib/proot-distro/installed-rootfs/kali/
###
wget -O kali/bin/vnc https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/Proot/vnc
###
chmod 700 kali/bin/vnc
###
wget -O $PREFIX/bin/nethunter https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/Proot/nethunter
###
chmod 700 $PREFIX/bin/nethunter
###
ln -s $PREFIX/bin/nethunter $PREFIX/bin/kali
###
wget -O kali/root/.zshrc https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/Proot/.zshrc
###
sed -i '/if/,/fi/d' kali/root/.bash_profile
###
echo "nameserver 9.9.9.9" > kali/etc/resolv.conf
###
chmod +s kali/usr/bin/sudo
###
chmod +s kali/usr/bin/su
###
echo "kali    ALL=(ALL:ALL) ALL" > kali/etc/sudoers.d/kali
###
echo "Set disable_coredump false" > kali/etc/sudo.conf
###
echo "
(kali vnc) &
kali
" >> $PREFIX/etc/bash.bashrc
###
echo "
[*] Successful Installation!
[*] Type: kali vnc passwd
[*] Type: kali vnc &
"
###
USRID=$(id -u)
GRPID=$(id -g)
kali -r usermod -u "$USRID" kali 2>/dev/null
kali -r groupmod -g "$GRPID" kali 2>/dev/null
