#!/data/data/com.termux/files/usr/bin/bash -e

echo 'DISTRO_NAME="Kali Linux Full"' > $PREFIX/etc/proot-distro/kali-full.sh
###
echo "
clear
kali
" >>$PREFIX/etc/bash.bashrc
###
echo "pd sh kali-full" > $PREFIX/bin/kali
###
chmod 700 $PREFIX/bin/kali
###
mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs/kali-full
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
axel -a --search -o kali-full.tar.xz https://kali.download/nethunter-images/current/rootfs/kali-nethunter-rootfs-full-arm64.tar.xz
###
echo "
[*] Extracting rootfs...
"
###
proot --link2symlink bsdtar -xpJf kali-full.tar.xz 2>/dev/null
###
echo "
[*] Done!
"
###
mv chroot/kali-arm64/* $PREFIX/var/lib/proot-distro/installed-rootfs/kali-full
###
rm -rf chroot
###
wget -O kali-full/root/.zshrc https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/Proot/.zshrc
###
echo "nameserver 9.9.9.9" > kali-full/etc/resolv.conf
###
git clone https://github.com/zsh-users/zsh-autosuggestions kali-full/root/.zsh/zsh-autosuggestions
###
echo "
To login Kali type: kali
"
