#!/bin/sh

echo 'DISTRO_NAME="Kali Linux Full"' >> $PREFIX/etc/proot-distro/kali-full.sh
###
echo "pd sh kali-full" > $PREFIX/bin/kali
###
chmod 700 $PREFIX/bin/kali
###
mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs/kali-full
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
axel -a -n 1 -o kali-full.tar.xz https://kali.download/nethunter-images/current/rootfs/kali-nethunter-rootfs-full-arm64.tar.xz
###
echo "
[*] Extracting rootfs...
"
###
bsdtar -xpJf kali-full.tar.xz >/dev/null 2>&1
###
echo "
[*] Done!
"
###
mv chroot/kali-arm64/* $PREFIX/var/lib/proot-distro/installed-rootfs/kali-full
###
rm -rf chroot
###
echo "
To login Kali type: kali
"
