#!/bin/sh

echo 'DISTRO_NAME="Kali Minimal"' >> $PREFIX/etc/proot-distro/kali-minimal.sh
###
mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
wget https://github.com/xiv3r/Kali-Linux-Nethunter/releases/download/rootfs/kali-nethunter-minimal-rootfs-arm64.tar.xz
###
tar -xvJf kali-nethunter-minimal-rootfs-arm64.tar.xz
###
echo "
To login Parrot Sec: pd sh kali-minimal
"
pd sh kali-minimal
