#!/data/data/com.termux/files/usr/bin/bash -e

apt install axel bsdtar proot-distro proot neofetch -y
### Ascii
neofetch --ascii_distro Kali -L
###
mkdir -p $PREFIX/var/lib/proot-distro/installed-rootfs/kali-minimal
###
cd $PREFIX/var/lib/proot-distro/installed-rootfs
###
RFS=kali-arm64
FS=kali-minimal
NM=Kali
axel -a --search -o ${FS}.tar.xz https://kali.download/nethunter-images/current/rootfs/kali-nethunter-rootfs-minimal-arm64.tar.xz
###
echo "[*] Extracting rootfs...!!!"
###
proot --link2symlink bsdtar -xpJf ${FS}.tar.xz 2>/dev/null
###
cat >$PREFIX/etc/proot-distro/${FS}.sh << EOF
DISTRO_NAME="${NM} Nethunter Minimal"
EOF
###
echo "pd sh ${FS}" > $PREFIX/bin/kali
termux-fix-shebang $PREFIX/bin/kali
chmod 700 $PREFIX/bin/kali
###
echo "
clear
kali
" >>$PREFIX/etc/bash.bashrc
###
mv ${RFS}/* $PREFIX/var/lib/proot-distro/installed-rootfs/${FS}
###
rm -rf ${RFS}
###
wget -O ${FS}/root/.zshrc https://raw.githubusercontent.com/xiv3r/Termux-Pentesting-Distro/refs/heads/main/KaliLinux/Proot/.zshrc
###
echo "To login ${NM} Linux type: kali"
