#!/data/data/com.termux/files/usr/bin/bash

# Install required packages
apt install proot proot-distro bsdtar axel neofetch -y
clear

# Display the menu
echo "Please select the Distro:"
echo "1. alma"
echo "2. alpine"
echo "3. altlinux"
echo "4. amazon"
echo "5. archlinux"
echo "6. artix"
echo "7. backbox"
echo "8. blackarch"
echo "9. centos"
echo "10. chimera"
echo "11. fedora"
echo "12. gentoo"
echo "13. debian"
echo "14. debkali"
echo "15. deepin"
echo "16. devuan"
echo "17. kali"
echo "18. manjaro"
echo "19. openkylin"
echo "20. openwrt"
echo "21. openeuler"
echo "22. opensuse"
echo "23. oracle"
echo "24. parrot"
echo "25. pardus"
echo "26. photon"
echo "27. rocky"
echo "28. ubuntu"
echo "29. ujammy"
echo "30. void"

# Read the user's choice
read -p "Enter the number: " choice

# Set the FS variable based on the user's choice
case $choice in
    1)
        FS="alma"
        ;;
    2)
        FS="alpine"
        ;;
    3)
        FS="altlinux"
        ;;
    4)
        FS="amazon"
        ;;
    5)
        FS="archlinux"
        ;;
    6)
        FS="artix"
        ;;
    7)
        FS="backbox"
        ;;
    8)
        FS="blackarch"
        ;;
    9)
        FS="centos"
        ;;
    10)
        FS="chimera"
        ;;
    11)
        FS="fedora"
        ;;
    12)
        FS="gentoo"
        ;;
    13)
        FS="debian"
        ;;
    14)
        FS="debkali"
        ;;
    15)
        FS="deepin"
        ;;
    16)
        FS="devuan"
        ;;
    17)
        FS="kali"
        ;;
    18)
        FS="manjaro"
        ;;
    19)
        FS="openkylin"
        ;;
    20)
        FS="openwrt"
        ;;
    21)
        FS="openeuler"
        ;;
    22)
        FS="opensuse"
        ;;
    23)
        FS="oracle"
        ;;
    24)
        FS="parrot"
        ;;
    25)
        FS="pardus"
        ;;
    26)
        FS="photon"
        ;;
    27)
        FS="rocky"
        ;;
    28)
        FS="ubuntu"
        ;;
    29)
        FS="ujammy"
        ;;
    30)
        FS="void"
        ;;
    *)
        echo "Invalid selection. Exiting."
        exit 1
        ;;
esac

clear

# Read FS value
FS="$FS"

# Forward the value of FS to NM
NM="$FS"

# Capitalize the first letter of NM
NM=$(echo "$NM" | awk '{print toupper(substr($0,1,1)) substr($0,2)}')

# Display the values of FS and NM
echo "$FS" > /dev/null
echo "$NM" > /dev/null

# Display neofetch with custom ASCII art
neofetch --ascii_distro "${NM}"

# Create necessary directories
mkdir -p "$PREFIX/var/lib/proot-distro/installed-rootfs"

# Change directory
cd "$PREFIX/var/lib/proot-distro/installed-rootfs/"

# Download the rootfs using axel
axel -a -o "${FS}.tar.xz" "https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/${FS}.tar.xz"

# Extract the rootfs
echo "[*] Extracting ${NM} Linux Rootfs, Please wait...!!!"
proot --link2symlink bsdtar -xpJf "${FS}.tar.xz" 2>/dev/null

# Create a proot-distro configuration file for the Kali minimal rootfs
cat > "$PREFIX/etc/proot-distro/${FS}.sh" << EOF
DISTRO_NAME="${NM} Linux"
TARBALL_URL['aarch64']="https://github.com/xiv3r/Termux-Pentesting-Distro/releases/download/rootfs/${FS}.tar.xz"
TARBALL_SHA256['aarch64']="$(sha256sum "${FS}.tar.xz" | awk '{print $1}')"
EOF

# Create a shortcut command to launch the distro
cat > "$PREFIX/bin/${FS}" << EOF
#!/data/data/com.termux/files/usr/bin/bash

proot-distro login ${FS}
EOF

# Fix shebang and set executable permissions
termux-fix-shebang "$PREFIX/bin/${FS}"
chmod 700 "$PREFIX/bin/${FS}"

# Add start-up login notification
cat >> $PREFIX/etc/bash.bashrc << EOF
echo "Login ${NM} Linux: ${FS}"
EOF

# Add support for uninstallation
cat > $PREFIX/bin/uninstall-${FS} << EOF
#!/data/data/com.termux/files/usr/bin/bash

proot-distro remove ${FS}
sed -i 's/echo "Login ${NM} Linux: ${FS}"//g' $PREFIX/etc/bash.bashrc
rm -rf $PREFIX/bin/uninstall-${FS}
rm -rf $PREFIX/bin/${FS}
rm -rf $PREFIX/var/lib/proot-distro/dlcache/${FS}.tar.xz
EOF
chmod 700 "$PREFIX/bin/uninstall-${FS}"

# Backup tarball to the cache
mkdir -p "$PREFIX/var/lib/proot-distro/dlcache"
mv "${FS}.tar.xz" "$PREFIX/var/lib/proot-distro/dlcache"

# Display final instructions
echo -e '\e[1;93m'
cat << EOF
Successful Installation!

To login ${NM} Linux, Type: ${FS}
EOF
